"""Cross-platform icons drawn from the bundled Lucide set.

[`Icon`][pythonnative.Icon] renders any of the 1,800+ Lucide icons as a
vector [`Svg`][pythonnative.Svg], so the same name looks the same on iOS,
Android, and in the browser preview, and one ``color`` prop tints every
icon:

```python
import pythonnative as pn

pn.Row(
    pn.Icon("heart", size=20, color="#E11D48"),
    pn.Text("Favorites"),
    style=pn.style(spacing=8, align_items="center"),
)
```

Names are the Lucide names (``"house"``, ``"settings"``,
``"chevron-right"``); browse them at https://lucide.dev/icons. The
[`IconName`][pythonnative.icons.IconName] literal gives editors
completion and type checkers a way to catch typos. Tab bars accept the
same names through ``tab_bar_icon``.

The icon data ships with PythonNative (``_lucide.json``, ISC license,
regenerated by ``scripts/generate-icons.py``); nothing is downloaded at
runtime.
"""

from __future__ import annotations

import json
from functools import lru_cache
from typing import TYPE_CHECKING, Any, Dict, List, Optional, Tuple, cast

from ..element import Element
from ..style import Color, Style, StyleProp
from ._names import ICON_NAMES, LUCIDE_VERSION, IconName

if TYPE_CHECKING:
    from ..svg import SvgShape

__all__ = [
    "ICON_NAMES",
    "ICON_VIEW_BOX",
    "Icon",
    "IconName",
    "IconSpec",
    "LUCIDE_VERSION",
    "icon_names",
    "icon_shapes",
    "is_icon_name",
    "tab_icon_spec",
]

ICON_VIEW_BOX = "0 0 24 24"
"""Every bundled icon is drawn on a 24 by 24 grid."""

_ICON_NAME_SET = frozenset(ICON_NAMES)


@lru_cache(maxsize=1)
def _data() -> Dict[str, Any]:
    from importlib.resources import files

    return json.loads(files(__package__).joinpath("_lucide.json").read_text(encoding="utf-8"))


def icon_names() -> Tuple[str, ...]:
    """Every available icon name, sorted."""
    return ICON_NAMES


def is_icon_name(name: Any) -> bool:
    """Whether ``name`` is a bundled icon."""
    return isinstance(name, str) and name in _ICON_NAME_SET


def _suggest(name: str) -> List[str]:
    import difflib

    return difflib.get_close_matches(name, ICON_NAMES, n=3, cutoff=0.6)


@lru_cache(maxsize=512)
def icon_shapes(name: str) -> Tuple[Dict[str, Any], ...]:
    """The flattened shape records that draw ``name``.

    The records are what an ``Svg`` element carries in its ``shapes``
    prop: path shapes as ``{"kind": "path", "d": ...}``, and the other
    basic shapes with their geometry. Paint is left to the ``Svg`` root.

    Raises:
        KeyError: If the icon doesn't exist. The message lists close
            matches.
    """
    icons = _data()["icons"]
    try:
        raw = icons[name]
    except KeyError:
        hint = _suggest(name)
        suffix = f" Did you mean {', '.join(repr(h) for h in hint)}?" if hint else ""
        raise KeyError(f"Unknown icon {name!r}.{suffix} See https://lucide.dev/icons") from None
    shapes: List[Dict[str, Any]] = []
    for item in raw:
        if isinstance(item, str):
            shapes.append({"kind": "path", "d": item})
        else:
            shapes.append(dict(item))
    return tuple(shapes)


def Icon(
    name: IconName,
    *,
    size: float = 24,
    color: Optional[Color] = None,
    stroke_width: float = 2,
    fill: Optional[Color] = None,
    style: StyleProp = None,
    accessibility_label: Optional[str] = None,
    test_id: Optional[str] = None,
    key: Optional[str] = None,
) -> Element:
    """Render a bundled vector icon.

    Icons are stroke based: ``color`` sets the stroke, and ``fill`` (off
    by default) fills the enclosed areas, which is how a "solid" variant
    is made.

    Args:
        name: A Lucide icon name such as ``"heart"`` or ``"chevron-right"``.
        size: Width and height in logical points.
        color: Stroke color. Defaults to the platform label color.
        stroke_width: Stroke width on the 24-unit grid (``2`` is the Lucide
            default; ``1.5`` reads lighter, ``2.5`` bolder).
        fill: Optional fill color for a solid look.
        style: Extra styles (margins, opacity, transforms). ``width`` and
            ``height`` in ``style`` override ``size``.
        accessibility_label: Spoken description. Icons without a label are
            hidden from assistive technology, since a decorative icon next
            to text shouldn't be read twice.
        test_id: Stable identifier for UI tests.
        key: Stable identity for keyed reconciliation.

    Returns:
        An [`Element`][pythonnative.Element] of type ``"Svg"``.

    Raises:
        KeyError: If ``name`` isn't a bundled icon.

    Example:
        ```python
        pn.Icon("settings", size=20, color="#6B7280")
        pn.Icon("star", fill="#F59E0B", color="#F59E0B")
        ```
    """
    from ..components.graphics import Svg
    from ..style import StyleSheet

    # Icon records are already flattened wire dicts; ``Svg`` passes them through.
    shapes = cast("List[SvgShape]", list(icon_shapes(name)))
    merged: Style = {"width": size, "height": size}
    merged.update(StyleSheet.flatten(style))
    return Svg(
        shapes=shapes,
        view_box=ICON_VIEW_BOX,
        fill=fill or "none",
        stroke=color or "currentColor",
        stroke_width=stroke_width,
        stroke_linecap="round",
        stroke_linejoin="round",
        style=merged,
        accessibility_label=accessibility_label,
        accessible=True if accessibility_label else False,
        test_id=test_id,
        key=key,
    )


IconSpec = Dict[str, Any]
"""The wire form of a tab bar icon: ``{"shapes": [...], "view_box": ...}`` or ``{"uri": ...}``."""


def tab_icon_spec(icon: Any) -> IconSpec:
    """Resolve a ``tab_bar_icon`` value into its wire record.

    Args:
        icon: An icon name or an [`Asset`][pythonnative.Asset] (a bundled
            PNG, drawn as a template image).

    Raises:
        TypeError: For other values, including the removed
            ``{"ios": ..., "android": ...}`` dictionaries.
        KeyError: If a name isn't a bundled icon.
    """
    from ..assets import Asset

    if isinstance(icon, Asset):
        return {"uri": icon.uri}
    if isinstance(icon, str):
        if icon.startswith("asset://"):
            return {"uri": icon}
        return {"shapes": list(icon_shapes(icon)), "view_box": ICON_VIEW_BOX}
    raise TypeError(
        "tab_bar_icon must be an icon name (see pythonnative.icons) or pn.asset(...); "
        f"got {type(icon).__name__}. Platform dictionaries are no longer supported."
    )
