"""The dependency-free QR code encoder behind the dev-client connect link."""

from __future__ import annotations

import dataclasses
import hashlib
import re
import xml.etree.ElementTree as ET
from typing import List, Optional, Tuple

import pytest

from pythonnative.devserver import qr

CONNECT_URL = "pn-com.pythonnative.go://connect?url=ws%3A%2F%2F192.168.1.23%3A8081%2F%3Ftoken%3D0123456789abcdef"


def _digest(code: qr.QRCode) -> str:
    rows = ("".join("1" if dark else "0" for dark in row) for row in code.modules)
    return hashlib.sha256("\n".join(rows).encode()).hexdigest()


# Known answers generated by this encoder and checked module for module
# against segno 1.6.6 (same version, mask, and mode) and, for byte mode,
# the qrcode package. The digest is SHA-256 over rows of "0"/"1" joined by
# newlines.
VECTORS: List[Tuple[str, str, Optional[int], Optional[int], int, int, str]] = [
    ("HELLO WORLD", "Q", None, None, 1, 1, "9e1a2e4bb77f9908f8150a42cf275dfa0a9381ba05fe4b4ef3878253ce7ad5c7"),
    ("01234567", "M", None, None, 1, 3, "b3ee0aa5a65d5158b26ff0090a9539d5df3f23cc33c49c78dfa74a30b789a71d"),
    ("A", "H", None, None, 1, 4, "f363370148554d40d7215e74919591603d94fe445e2dc05df20473fdc6f93656"),
    (CONNECT_URL, "M", None, None, 6, 6, "6c38c64e033fa8a9cacbc1cc4e98c4d93e33527473fbf77daba0b807be150114"),
    (CONNECT_URL, "L", None, None, 5, 4, "09798f968a5d96288da73c73ec6907d38d795b3450147dd9cf04e2b4b3041a3e"),
    (
        "héllo wörld ✓ 日本語 🚀",
        "H",
        None,
        None,
        4,
        5,
        "b6362944c0a38d903569a40b28e4122eed4f710320fd452ed47330511b5ef6e5",
    ),
    (
        "https://pythonnative.dev/" + "docs/" * 30,
        "M",
        None,
        None,
        9,
        2,
        "886568509c8e22c1bf6602698064c12b5db0cf3ac476093fb108d76439b5a9d0",
    ),
    ("PythonNative " * 160, "L", None, None, 34, 2, "09624ee6b454ece392c1ee4d5b4cc9e0afb4c6e1819bf401a8f4f21036779170"),
    ("hi", "Q", 40, 3, 40, 3, "eefc017ebfe553a3561fe1fcbc286455ad13df4e73ef71507402bfef946f1e86"),
]


@pytest.mark.parametrize(
    "text, error, version, mask, want_version, want_mask, digest",
    VECTORS,
    ids=[f"{len(v[0])}chars-{v[1]}-v{v[4]}" for v in VECTORS],
)
def test_known_answers(
    text: str,
    error: str,
    version: Optional[int],
    mask: Optional[int],
    want_version: int,
    want_mask: int,
    digest: str,
) -> None:
    code = qr.encode(text, error=error, version=version, mask=mask)
    assert (code.version, code.mask, code.error) == (want_version, want_mask, error)
    assert _digest(code) == digest


# ── Structure ──────────────────────────────────────────────────────────


def _finder_at(code: qr.QRCode, left: int, top: int) -> bool:
    for dy in range(7):
        for dx in range(7):
            ring = max(abs(dx - 3), abs(dy - 3))
            if code[left + dx, top + dy] != (ring != 2):
                return False
    return True


@pytest.mark.parametrize("version", [1, 2, 7, 14, 40])
def test_function_patterns(version: int) -> None:
    code = qr.encode("structure", version=version, mask=version % 8)
    size = code.size
    assert size == 4 * version + 17
    assert len(code.modules) == size and all(len(row) == size for row in code.modules)
    assert all(isinstance(dark, bool) for row in code.modules for dark in row)
    for left, top in ((0, 0), (size - 7, 0), (0, size - 7)):
        assert _finder_at(code, left, top)
    # Separators around the finders are light.
    for i in range(8):
        assert not code[7, i] and not code[i, 7]
        assert not code[size - 8, i] and not code[size - 1 - i, 7]
        assert not code[7, size - 1 - i] and not code[i, size - 8]
    for i in range(8, size - 8):
        assert code[i, 6] == (i % 2 == 0)
        assert code[6, i] == (i % 2 == 0)
    assert code[8, size - 8]  # The dark module.
    if version > 1:
        # The bottom-right alignment pattern is centered at (size - 7, size - 7).
        center = size - 7
        for dy in range(-2, 3):
            for dx in range(-2, 3):
                assert code[center + dx, center + dy] == (max(abs(dx), abs(dy)) != 1)


def _format_bits(code: qr.QRCode) -> Tuple[int, int]:
    size = code.size
    first = [code[8, i] for i in range(6)] + [code[8, 7], code[8, 8], code[7, 8]]
    first += [code[14 - i, 8] for i in range(9, 15)]
    second = [code[size - 1 - i, 8] for i in range(8)] + [code[8, size - 15 + i] for i in range(8, 15)]
    return sum(bit << i for i, bit in enumerate(first)), sum(bit << i for i, bit in enumerate(second))


@pytest.mark.parametrize(
    "error, mask, expected",
    [
        ("M", 0, 0b101010000010010),
        ("L", 4, 0b110011000101111),
        ("Q", 6, 0b010111011011010),
        ("H", 2, 0b001110011100111),
    ],
)
def test_format_information(error: str, mask: int, expected: int) -> None:
    code = qr.encode("FORMAT", error=error, mask=mask)
    assert _format_bits(code) == (expected, expected)


@pytest.mark.parametrize("version, expected", [(7, 0x07C94), (21, 0x15683), (40, 0x28C69)])
def test_version_information(version: int, expected: int) -> None:
    code = qr.encode("v", version=version, mask=0)
    size = code.size
    bottom_left = sum(code[i // 3, size - 11 + i % 3] << i for i in range(18))
    top_right = sum(code[size - 11 + i % 3, i // 3] << i for i in range(18))
    assert bottom_left == top_right == expected


def test_qrcode_is_frozen() -> None:
    code = qr.encode("frozen")
    with pytest.raises(dataclasses.FrozenInstanceError):
        code.version = 2  # type: ignore[misc]
    assert code == qr.encode("frozen")


# ── Modes, versions, and capacity ──────────────────────────────────────


@pytest.mark.parametrize(
    "char, count, version",
    [
        ("1", 41, 1),  # Numeric capacity of 1-L.
        ("1", 42, 2),
        ("A", 25, 1),  # Alphanumeric capacity of 1-L.
        ("A", 26, 2),
        ("a", 17, 1),  # Byte capacity of 1-L.
        ("a", 18, 2),
        ("é", 8, 1),  # Byte mode counts UTF-8 bytes, not characters.
        ("é", 9, 2),
        ("1", 7089, 40),
        ("A", 4296, 40),
        ("a", 2953, 40),
    ],
)
def test_smallest_version_that_fits(char: str, count: int, version: int) -> None:
    # A fixed mask skips the penalty search; the version choice doesn't depend on it.
    assert qr.encode(char * count, error="L", mask=0).version == version


@pytest.mark.parametrize("char, count, error", [("1", 7090, "L"), ("A", 4297, "L"), ("a", 2954, "L"), ("a", 1274, "H")])
def test_input_too_long(char: str, count: int, error: str) -> None:
    with pytest.raises(ValueError, match="don't fit"):
        qr.encode(char * count, error=error)


def test_forced_version_too_small() -> None:
    with pytest.raises(ValueError, match="version 1"):
        qr.encode("a" * 30, version=1)


@pytest.mark.parametrize("kwargs", [{"error": "X"}, {"error": "m"}, {"version": 0}, {"version": 41}, {"mask": 8}])
def test_invalid_arguments(kwargs: dict) -> None:
    with pytest.raises(ValueError):
        qr.encode("x", **kwargs)


def test_empty_text() -> None:
    code = qr.encode("")
    assert code.version == 1


# ── Rendering ──────────────────────────────────────────────────────────


def _from_terminal(text: str, border: int, invert: bool) -> List[List[bool]]:
    halves = {"█": (True, True), "▀": (True, False), "▄": (False, True), " ": (False, False)}
    rows: List[List[bool]] = []
    for line in text.split("\n"):
        rows.append([halves[ch][0] for ch in line])
        rows.append([halves[ch][1] for ch in line])
    # Filled means light by default and dark when inverted.
    return [[filled == invert for filled in row[border : -border or None]] for row in rows[border:]]


@pytest.mark.parametrize("border", [0, 1, 2, 4])
@pytest.mark.parametrize("invert", [False, True])
def test_terminal_round_trips(border: int, invert: bool) -> None:
    code = qr.encode(CONNECT_URL)
    text = qr.to_terminal(code, border=border, invert=invert)
    lines = text.split("\n")
    width = code.size + 2 * border
    assert len(lines) == (width + 1) // 2
    assert all(len(line) == width for line in lines)
    assert set(text) <= {"█", "▀", "▄", " ", "\n"}
    decoded = _from_terminal(text, border, invert)
    assert decoded[: code.size] == [list(row) for row in code.modules]


def test_terminal_quiet_zone() -> None:
    code = qr.encode("quiet")
    width = code.size + 4
    lines = qr.to_terminal(code).split("\n")
    # Light modules are filled by default, so the quiet zone is solid.
    assert lines[0] == "█" * width
    assert all(line[:2] == "██" and line[-2:] == "██" for line in lines[:-1])
    # The symbol has an odd height, so the last line's lower half is background.
    assert lines[-1] == "▀" * width
    # The top-left finder corner is dark, drawn as background.
    assert lines[1][2] == " "
    inverted = qr.to_terminal(code, invert=True).split("\n")
    assert inverted[0] == " " * width and inverted[-1] == " " * width
    assert inverted[1][2] == "█"


def test_terminal_rejects_negative_border() -> None:
    with pytest.raises(ValueError):
        qr.to_terminal(qr.encode("x"), border=-1)


SVG = "{http://www.w3.org/2000/svg}"


def test_svg_is_well_formed_and_matches_modules() -> None:
    code = qr.encode(CONNECT_URL)
    markup = qr.to_svg(code, border=4, scale=3)
    root = ET.fromstring(markup)
    width = code.size + 8
    assert root.tag == f"{SVG}svg"
    assert root.get("viewBox") == f"0 0 {width} {width}"
    assert root.get("width") == root.get("height") == str(width * 3)
    assert root.get("shape-rendering") == "crispEdges"
    paths = root.findall(f"{SVG}path")
    assert len(paths) == 1
    assert root.find(f"{SVG}rect") is not None
    painted = [[False] * code.size for _ in range(code.size)]
    for x, y, length in re.findall(r"M(\d+) (\d+)h(\d+)v1h-\3z", paths[0].get("d", "")):
        for dx in range(int(length)):
            painted[int(y) - 4][int(x) - 4 + dx] = True
    assert painted == [list(row) for row in code.modules]


def test_svg_colors_are_escaped() -> None:
    root = ET.fromstring(qr.to_svg(qr.encode("x"), dark='"/><script/>', light="#fafafa"))
    path = root.find(f"{SVG}path")
    rect = root.find(f"{SVG}rect")
    assert path is not None and rect is not None
    assert path.get("fill") == '"/><script/>'
    assert rect.get("fill") == "#fafafa"


@pytest.mark.parametrize("kwargs", [{"border": -1}, {"scale": 0}])
def test_svg_rejects_bad_arguments(kwargs: dict) -> None:
    with pytest.raises(ValueError):
        qr.to_svg(qr.encode("x"), **kwargs)
