package com.pythonnative.runtime.plugins

import com.pythonnative.runtime.bridge.PNRegistry

/**
 * Plugin registrations generated by `pn build`.
 *
 * The build tool overwrites this file with one `register` call per
 * plugin entry declared in the project's `pythonnative.plugins` entry
 * points. Nothing else may depend on its content beyond [registerAll].
 */
object GeneratedPlugins {
    /** Register every generated plugin with `registry`. */
    @Suppress("UNUSED_PARAMETER")
    fun registerAll(registry: PNRegistry) {}
}
