// Generated by scripts/generate-native-contracts.py.
import Foundation
import PythonNativeKit

public struct PNNativeFixtureNote: Codable {
    public let `required`: String?
    public let `optional`: PNPresence<String?>
    public init(`required`: String?, `optional`: PNPresence<String?>) {
        self.`required` = `required`
        self.`optional` = `optional`
    }
    private enum CodingKeys: String, CodingKey { case `required`; case `optional` }
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.`required` = try container.decode(String?.self, forKey: .`required`)
        self.`optional` = container.contains(.`optional`) ? .present(try container.decode(String?.self, forKey: .`optional`)) : .absent
    }
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(`required`, forKey: .`required`)
        if case .present(let value) = `optional` { try container.encode(value, forKey: .`optional`) }
    }
}

public enum PNPNNativeFixtureDefaultLabel: String, Codable {
    case `_total__quoted___path___` = "$total \"quoted\" \\path\n\u{0}\u{8}"
    case `ready` = "ready"
}

public struct PNNativeFixtureDefault: Codable {
    public let `note`: PNNativeFixtureNote
    public let `label`: PNPNNativeFixtureDefaultLabel
    public let `nullable`: String?
    public init(`note`: PNNativeFixtureNote, `label`: PNPNNativeFixtureDefaultLabel, `nullable`: String?) {
        self.`note` = `note`
        self.`label` = `label`
        self.`nullable` = `nullable`
    }
    private enum CodingKeys: String, CodingKey { case `note`; case `label`; case `nullable` }
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.`note` = try container.decode(PNNativeFixtureNote.self, forKey: .`note`)
        self.`label` = container.contains(.`label`) ? (try container.decode(PNPNNativeFixtureDefaultLabel.self, forKey: .`label`)) : (try PNValues.decode(PNPNNativeFixtureDefaultLabel.self, PNValues.defaultValue("\"$total \\\"quoted\\\" \\\\path\\n\\u0000\\b\"")))
        self.`nullable` = container.contains(.`nullable`) ? (try container.decode(String?.self, forKey: .`nullable`)) : (try PNValues.decode(String?.self, PNValues.defaultValue("null")))
    }
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(`note`, forKey: .`note`)
        try container.encode(`label`, forKey: .`label`)
        try container.encode(`nullable`, forKey: .`nullable`)
    }
}
