// Generated by `pn build`. Do not edit: the PythonNative build tool
// overwrites this file with one `register(into:)` call per bundled plugin.

/// Registration hook for plugins copied into `Sources/Plugins` by `pn build`.
public enum PNGeneratedPlugins {
    /// Register every generated plugin into `registry`.
    public static func registerAll(into registry: PNRegistry) {}
}
