#!/usr/bin/env python3
"""Regenerate checked-in built-in contracts and the bundled iOS test fixtures."""

import json
import shutil
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Literal, NotRequired, TypedDict

import pythonnative  # noqa: F401  # Install built-in schemas in a clean process.
from pythonnative.sdk.codegen import generate
from pythonnative.sdk.contract_codegen import ContractCompiler
from pythonnative.sdk.native_types import NativeTypes, quoted
from pythonnative.sdk.types import type_schema

ROOT = Path(__file__).resolve().parents[1]
NATIVE = ROOT / "src/pythonnative/native"


class NativeFixtureNote(TypedDict):
    """Exercise required null and nonrequired nullable fields in both compilers."""

    required: str | None
    optional: NotRequired[str | None]


@dataclass
class NativeFixtureDefault:
    """Exercise nested defaults and language-specific literal escaping."""

    note: NativeFixtureNote
    label: Literal['$total "quoted" \\path\n\x00\b', "ready"] = '$total "quoted" \\path\n\x00\b'
    nullable: str | None = None


def validation_fixtures(kotlin: bool) -> str:
    """Compile the shared schema corpus using the production predicate compiler."""
    compiler = ContractCompiler(kotlin)
    cases = json.loads((ROOT / "tests/contracts/validation.json").read_text())
    names = [compiler.predicate(item["schema"]) for item in cases]
    template = (ROOT / "src/pythonnative/sdk/templates" / ("contracts.kt" if kotlin else "contracts.swift")).read_text()
    if kotlin:
        helpers = template.split("    private fun isBoolean", 1)[1].split("    fun validate(", 1)[0]
        dispatch = (
            "    fun matches(index: Int, value: Any): Boolean = when (index) {\n"
            + "\n".join(f"        {i} -> {name}(value)" for i, name in enumerate(names))
            + "\n        else -> false\n    }"
        )
        return (
            "\nobject PNValidationFixtures {\n    private fun isBoolean"
            + helpers
            + "\n"
            + "\n".join(compiler.functions)
            + "\n"
            + dispatch
            + "\n}\n"
        )
    helpers = template.split("    private static func isBoolean", 1)[1].split("    public static func validate(", 1)[0]
    dispatch = (
        "    static func matches(_ index: Int, _ value: Any) -> Bool {\n        switch index {\n"
        + "\n".join(f"        case {i}: return {name}(value)" for i, name in enumerate(names))
        + "\n        default: return false\n        }\n    }"
    )
    return (
        "\nimport CoreFoundation\nenum PNValidationFixtures {\n    private static func isBoolean"
        + helpers
        + "\n"
        + "\n".join(compiler.functions)
        + "\n"
        + dispatch
        + "\n}\n"
    )


def list_fixtures(kotlin: bool) -> str:
    """Embed one shared list trace so XCTest needs no extra bundle resource."""
    payload = json.dumps(json.loads((ROOT / "tests/contracts/list-trace.json").read_text()), separators=(",", ":"))
    if kotlin:
        return "\nobject PNListFixtures { val trace = " + quoted(payload, kotlin=True) + " }\n"
    return "\nenum PNListFixtures { static let trace = " + quoted(payload) + " }\n"


def record_fixtures() -> dict[Path, str]:
    """Generate native test records from real Python annotations."""
    types = NativeTypes()
    types.types(type_schema(NativeFixtureDefault), "Fixture")
    return {
        NATIVE
        / "ios/Tests/PythonNativeKitTests/PNRecordFixtures.swift": (
            "// Generated by scripts/generate-native-contracts.py.\n"
            "import Foundation\nimport PythonNativeKit\n\n"
            + "\n".join(types.swift)
            + validation_fixtures(False)
            + list_fixtures(False)
        ),
        NATIVE
        / "android/src/test/java/com/pythonnative/generated/PNRecordFixtures.kt": (
            "// Generated by scripts/generate-native-contracts.py.\n"
            "package com.pythonnative.generated\n\n"
            "import org.json.JSONObject\nimport org.json.JSONArray\n\n"
            + "\n".join(types.kotlin)
            + validation_fixtures(True)
            + list_fixtures(True)
        ),
    }


def main() -> None:
    """Generate both native libraries from the same Python definitions."""
    with tempfile.TemporaryDirectory(prefix="pn-contracts-") as folder:
        generate(folder)
        for extension, destination in (
            ("swift", NATIVE / "ios/Sources/PythonNativeKit/Generated"),
            ("kt", NATIVE / "android/src/main/java/com/pythonnative/generated"),
        ):
            for name in ("PNContracts", "NativeProps", "NativeModules", "NativeValues"):
                shutil.copyfile(Path(folder) / f"{name}.{extension}", destination / f"{name}.{extension}")
    shutil.copyfile(
        ROOT / "tests/contracts/validation.json", NATIVE / "ios/Tests/PythonNativeKitTests/Fixtures/validation.json"
    )
    for path, content in record_fixtures().items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)


if __name__ == "__main__":
    main()
